import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { ScoreRing } from '../components/ScoreRing';
import { SessionPlanSkeleton } from '../components/Skeleton';

interface AgendaItem {
  timeRange: string;
  type: 'intro' | 'discussion' | 'exercise' | 'planning' | 'wrap-up';
  title: string;
  description: string;
}

interface FollowUpTask {
  title: string;
  priority: 'high' | 'medium' | 'low';
}

interface PlanData {
  sessionId: string;
  mentee: { displayName: string; initials: string; goal: string; skills: string[] };
  mentor: { displayName: string; initials: string; title: string; company: string };
  compatibilityScore: number;
  matchDescription: string;
  keyStrengths: string[];
  agenda: AgendaItem[];
  followUpTasks: FollowUpTask[];
}

const typeBadgeStyles: Record<string, string> = {
  intro: 'bg-blue/20 text-blue',
  discussion: 'bg-violet/20 text-violet-light',
  exercise: 'bg-rose/20 text-rose',
  planning: 'bg-amber/20 text-amber',
  'wrap-up': 'bg-white/5 text-text-secondary',
};

const priorityStyles: Record<string, string> = {
  high: 'bg-rose/20 text-rose',
  medium: 'bg-amber/20 text-amber',
  low: 'bg-mint/20 text-mint',
};

export default function SessionPlan() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<PlanData | null>(null);

  useEffect(() => {
    fetch(`/v1/sessions/${id ?? 'session-001'}/plan`)
      .then((r) => r.json())
      .then((d) => setData(d as PlanData));
  }, [id]);

  if (!data) {
    return <SessionPlanSkeleton />;
  }

  return (
    <section className="max-w-4xl mx-auto px-6 py-10">
      {/* Header: Mentee — Score — Mentor */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-6 mb-6">
        {/* Mentee card */}
        <div className="glass-card p-4 flex items-center gap-3 flex-1">
          <div className="w-12 h-12 rounded-full bg-mint/20 border-2 border-mint/40 flex items-center justify-center text-sm font-bold text-mint">
            {data.mentee.initials}
          </div>
          <div>
            <p className="font-semibold text-text-primary">{data.mentee.displayName}</p>
            <p className="text-xs text-text-secondary">{data.mentee.goal}</p>
          </div>
        </div>

        {/* Score ring (center) */}
        <div className="flex flex-col items-center">
          <ScoreRing score={data.compatibilityScore} size="lg" />
          <span className="mt-2 text-xs px-2 py-0.5 rounded-full bg-violet/20 text-violet-light font-medium">
            Generated by AI
          </span>
        </div>

        {/* Mentor card */}
        <div className="glass-card p-4 flex items-center gap-3 flex-1">
          <div className="w-12 h-12 rounded-full bg-violet/20 border-2 border-violet/40 flex items-center justify-center text-sm font-bold text-violet-light">
            {data.mentor.initials}
          </div>
          <div>
            <p className="font-semibold text-text-primary">{data.mentor.displayName}</p>
            <p className="text-xs text-text-secondary">{data.mentor.title} at {data.mentor.company}</p>
          </div>
        </div>
      </div>

      {/* Match description */}
      <p className="text-sm text-text-secondary italic text-center mb-4">
        {data.matchDescription}
      </p>

      {/* Key strengths */}
      <div className="flex items-center justify-center gap-2 mb-10 flex-wrap">
        <span className="text-sm text-text-secondary font-medium">Key strength:</span>
        {data.keyStrengths.map((skill) => (
          <span
            key={skill}
            className="text-xs px-2.5 py-1 rounded-full bg-violet/20 text-violet-light font-medium"
          >
            {skill}
          </span>
        ))}
      </div>

      {/* Agenda */}
      <section aria-label="Session agenda" className="mb-10">
        <h2 className="text-xl font-semibold mb-4" style={{ fontFamily: 'Outfit, sans-serif' }}>
          35-Minute Session Agenda
        </h2>
        <div className="space-y-3">
          {data.agenda.map((item, i) => (
            <div key={i} className="glass-card p-4 flex gap-4">
              <div className="shrink-0 w-24 text-sm text-text-muted font-mono">
                {item.timeRange}
              </div>
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${typeBadgeStyles[item.type] ?? ''}`}>
                    {item.type}
                  </span>
                  <h3 className="font-medium text-text-primary text-sm">{item.title}</h3>
                </div>
                <p className="text-sm text-text-secondary">{item.description}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Follow-up tasks */}
      <section aria-label="Follow-up tasks" className="mb-10">
        <h2 className="text-xl font-semibold mb-4" style={{ fontFamily: 'Outfit, sans-serif' }}>
          Follow-up Tasks
        </h2>
        <div className="space-y-2">
          {data.followUpTasks.map((task, i) => (
            <div key={i} className="glass-card p-4 flex items-center justify-between">
              <span className="text-sm text-text-primary">{task.title}</span>
              <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${priorityStyles[task.priority] ?? ''}`}>
                {task.priority}
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* Complete button */}
      <button className="btn-mint w-full text-base py-4">
        Mark My Sessions Complete &rarr;
      </button>
    </section>
  );
}
