namespace GuidedMentor.Content.Domain;

/// <summary>
/// Represents a personalised 35-minute mentorship session plan generated by AI.
/// Enforces invariants:
/// - SessionTitle: max 100 characters
/// - Agenda: 3-7 items, each at least 3 minutes, total exactly 35 minutes
/// - PreworkTasks: 2-5 items, each max 200 characters
/// - FollowUpTasks: 2-5 items, each max 200 characters
/// </summary>
public sealed record SessionPlan
{
    /// <summary>Title of the session. Maximum 100 characters.</summary>
    public string SessionTitle { get; init; }

    /// <summary>Timed agenda items. Must contain 3-7 items summing to exactly 35 minutes.</summary>
    public IReadOnlyList<AgendaItem> Agenda { get; init; }

    /// <summary>Pre-work tasks for the mentee. Must contain 2-5 items, each max 200 characters.</summary>
    public IReadOnlyList<string> PreworkTasks { get; init; }

    /// <summary>Follow-up tasks after the session. Must contain 2-5 items, each max 200 characters.</summary>
    public IReadOnlyList<string> FollowUpTasks { get; init; }

    public SessionPlan(
        string sessionTitle,
        IReadOnlyList<AgendaItem> agenda,
        IReadOnlyList<string> preworkTasks,
        IReadOnlyList<string> followUpTasks)
    {
        SessionTitle = sessionTitle;
        Agenda = agenda;
        PreworkTasks = preworkTasks;
        FollowUpTasks = followUpTasks;
    }

    /// <summary>
    /// Validates the session plan against all business invariants:
    /// - SessionTitle is not empty and at most 100 characters
    /// - Agenda has 3-7 items
    /// - Each agenda item has a duration of at least 3 minutes
    /// - Total agenda duration equals exactly 35 minutes
    /// - PreworkTasks has 2-5 items, each non-empty and at most 200 characters
    /// - FollowUpTasks has 2-5 items, each non-empty and at most 200 characters
    /// </summary>
    public bool IsValid() =>
        IsSessionTitleValid()
        && IsAgendaValid()
        && IsPreworkTasksValid()
        && IsFollowUpTasksValid();

    private bool IsSessionTitleValid() =>
        !string.IsNullOrWhiteSpace(SessionTitle)
        && SessionTitle.Length <= 100;

    private bool IsAgendaValid() =>
        Agenda.Count is >= 3 and <= 7
        && Agenda.All(a => a.DurationMinutes >= 3)
        && Agenda.Sum(a => a.DurationMinutes) == 35;

    private bool IsPreworkTasksValid() =>
        PreworkTasks.Count is >= 2 and <= 5
        && PreworkTasks.All(t => !string.IsNullOrWhiteSpace(t) && t.Length <= 200);

    private bool IsFollowUpTasksValid() =>
        FollowUpTasks.Count is >= 2 and <= 5
        && FollowUpTasks.All(t => !string.IsNullOrWhiteSpace(t) && t.Length <= 200);
}
